### PR TITLE
Inventory

### PR DESCRIPTION
**Pull request by tomasherout**
I made some changes related to host's inventory support.

Pleas, _ignore_ changes in imports `github.com/tpretz/terraform-provider-zabbix`  to my `github.com/tomasherout/terraform-provider-zabbix` in every file. In case of acceptance https://github.com/tpretz/go-zabbix-api/pull/5 I will change it back.

Quite bad is fact that Zabbix returns empty inventory as empty _array_ but non-empty inventory is _object_. This difference has led to more low-level access to data than should by fine.

### CODE REVIEW

**Comment by tpretz** [comment]
Had similar API issues with host interfaces i believe, when empty it was a 0 len array, but was an object when populated

https://github.com/tpretz/go-zabbix-api/blob/267ba9cc2cf114b8b742494f19682d04fbdd87d3/host.go#L57

I wonder if we can abstract the conditional json into the zabbix api library, and provide a clean struct over the boundary to this project
So, if they fix it in the future, just the other lib needs changes

**Comment by tomasherout** [comment]
> I wonder if we can abstract the conditional json into the zabbix api library, and provide a clean struct over the boundary to this project

I absolutely agree it's better way, but I am not sure how to do it correctly. `interfaces` is still array, also in case when there is one interface:

```json
{
    "jsonrpc": "2.0",
    "result": [
        {
            "hostid": "10385",
            "interfaces": [
                {
                    "interfaceid": "49",
                    "ip": "172.27.1.91"
                }
            ]
        }
    ],
    "id": 2
}
```

If I define https://github.com/tomasherout/go-zabbix-api/blob/inventory/host.go#L43 as type `Inventory` (instead of `json.RawMessage`), then unmarshaling in case (empty) array will fail. But, `Host` struct is used outside of `go-zabbix-api` project, so I can't have different struct for API clients and for server.

My idea is to have one struct for interacting with client (from provider) and different struct for interact with server. But, it will cause to copy same fileds _there and back_ almost everywhere.

Thanks for any better idea :)

**Comment by tomasherout** [comment]
Hello Thomas, in case of accepting https://github.com/tpretz/go-zabbix-api/pull/5 and releasing version this PR will be buildable after appropriate `required` change of course; currently works only with _replaced_ `require` - thank you for https://github.com/tpretz/go-zabbix-api/pull/5#issuecomment-739259632

**Comment by tpretz** [comment]
Finally had a chance to look at this.

Made a few changes, reverted your removal of applications (i need them to be present) but did refactor them into the backend module.

Also, made inventory a block, as saw how many options do exist for it.
Made the backend struct just a map (as looks like zabbix add stuff over time)
And, generate the frontend schema from an array, so we can easily add new attributes later.

**Pull request merged**
